### ISSUE TITLE
TypeError: invalid data

### ISSUE THREAD

**Issue by developeron29** [divshot/node-unzip-to-s3#4]
Now, While trying to upload a zip file containing some images, I am getting this error:
TypeError: invalid data

TypeError: invalid data
    at WriteStream.Socket.write (net.js:614:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:117:20)
    at /Users/ayushnarula/node_modules/unzip-to-s3/lib/index.js:69:22
    at /Users/ayushnarula/node_modules/unzip-to-s3/node_modules/knox-mpu/lib/multipartupload.js:373:20
    at Parser.<anonymous> (/Users/ayushnarula/node_modules/unzip-to-s3/node_modules/knox-mpu/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/Users/ayushnarula/node_modules/unzip-to-s3/node_modules/knox-mpu/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/Users/ayushnarula/node_modules/unzip-to-s3/node_modules/knox-mpu/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/Users/ayushnarula/node_modules/unzip-to-s3/node_modules/knox-mpu/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)

**Comment by developeron29** [comment]
Doing this worked for me:

```

var fs = require('fs');

var unzipToS3 = require('unzip-to-s3');

var stream = require('stream');
var util = require('util');

function StringifyStream(){
    stream.Transform.call(this);

    this._readableState.objectMode = false;
    this._writableState.objectMode = true;
}
util.inherits(StringifyStream, stream.Transform);

StringifyStream.prototype._transform = function(obj, encoding, cb){
    this.push(JSON.stringify(obj));
    cb();
};

var bucketUpload = unzipToS3.createClient({
    "key": '',
    "secret": '',
    "region": '',
    "bucket": ""
});

var zipStream = fs.createReadStream('./test.zip');

bucketUpload(zipStream).on('data', function (file) {

    console.log('file');
  //  console.log(file);

})
.pipe(new StringifyStream())
.pipe(process.stdout);
```
